import { Link } from 'react-router-dom';
import { Camera, Paintbrush, Truck } from 'lucide-react';

export default function HomePage() {
  return (
    <div className="flex flex-col">
      {/* Hero */}
      <section className="bg-brand-navy text-white py-24 px-4 sm:px-6 lg:px-8 text-center">
        <div className="max-w-4xl mx-auto space-y-8">
          <h1 className="text-5xl md:text-6xl font-extrabold tracking-tight">Turn Your Photo Into Stunning Wall Art</h1>
          <p className="text-xl text-gray-300 max-w-2xl mx-auto">AI-powered custom vinyl wall graphics featuring YOU.</p>
          <div className="pt-8">
            <Link to="/themes" className="inline-block bg-brand-gold hover:bg-brand-amber text-brand-navy font-bold text-lg px-8 py-4 rounded-full shadow-lg transition-transform hover:scale-105">
              Create Your Artwork
            </Link>
          </div>
        </div>
      </section>

      {/* How it Works */}
      <section className="py-24 bg-white px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <h2 className="text-3xl font-bold text-center text-brand-navy mb-16">How It Works</h2>
          <div className="grid md:grid-cols-3 gap-12 text-center">
            <div className="space-y-4">
              <div className="w-20 h-20 bg-brand-gold/10 rounded-full flex items-center justify-center mx-auto text-brand-gold">
                <Camera className="w-10 h-10" />
              </div>
              <h3 className="text-xl font-bold">1. Upload</h3>
              <p className="text-gray-600">Choose a theme and upload your favorite photo.</p>
            </div>
            <div className="space-y-4">
              <div className="w-20 h-20 bg-brand-gold/10 rounded-full flex items-center justify-center mx-auto text-brand-gold">
                <Paintbrush className="w-10 h-10" />
              </div>
              <h3 className="text-xl font-bold">2. Preview</h3>
              <p className="text-gray-600">Our AI generates your artwork. Request changes if needed.</p>
            </div>
            <div className="space-y-4">
              <div className="w-20 h-20 bg-brand-gold/10 rounded-full flex items-center justify-center mx-auto text-brand-gold">
                <Truck className="w-10 h-10" />
              </div>
              <h3 className="text-xl font-bold">3. Receive</h3>
              <p className="text-gray-600">We print on premium vinyl and ship to your door.</p>
            </div>
          </div>
        </div>
      </section>
      
      {/* Features */}
      <section className="py-24 bg-gray-50 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto text-center space-y-12">
           <h2 className="text-3xl font-bold text-brand-navy">Why Choose Us?</h2>
           <div className="grid md:grid-cols-3 gap-8">
             <div className="bg-white p-8 rounded-2xl shadow-sm">
               <h4 className="font-bold text-lg mb-2">Original Artwork</h4>
               <p className="text-gray-600">Every piece is 100% unique, generated by advanced AI for you.</p>
             </div>
             <div className="bg-white p-8 rounded-2xl shadow-sm">
               <h4 className="font-bold text-lg mb-2">Premium Vinyl</h4>
               <p className="text-gray-600">High-quality, durable vinyl that looks like it's painted on your wall.</p>
             </div>
             <div className="bg-white p-8 rounded-2xl shadow-sm">
               <h4 className="font-bold text-lg mb-2">UK Made</h4>
               <p className="text-gray-600">Produced and shipped locally from the UK for fast delivery.</p>
             </div>
           </div>
        </div>
      </section>
    </div>
  );
}
